[tool.poetry]
name = "p5-de"
version = "0.1.0"
description = ""
authors = ["alhassane-lab <ali75009@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.3.3"
ipykernel = "^6.30.1"
pymongo = "^4.15.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
